# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: PR Test

on:
  pull_request:
    branches:
      - '**'

jobs:
  unit-and-integration-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run unit tests
        run: ./gradlew test
      - name: Run integration tests
        run: ./gradlew integrationTest

  e2e-authentication-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          java-package: jdk
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Pull and Run OBS Websocket
        run: docker run -p 4444:4444 -d tinatiel/obswebsocket:latest
      - name: Run End2End Secured tests
        run: ./gradlew endToEndSecuredTest